### ISSUE TITLE
performance considerations QR used for q-sparse

### ISSUE THREAD

**Issue by QxGbM** [rioyokotalab/Hatrix#1]
Q { Uc | Uo } { Vc | Vo }

Option1: directly obtain Q from geqrf + orgqr then do gemms

Option2: store Q as Hv + tau from geqrf then do ormqrs

Fact1: many operations are A = Q * A. gemm does not accept in-place mat-mult, unless you copy after it is done.

Fact2: ormqr supports in-place mat-mult

Fact3: Hv+tau uses less storage

Concern1: how to reorder Uo ane Uc for ormqr?

Concern2: Is gemm drastically faster than ormqr?

**Comment by derpda** [comment]
I think geqrf -> orgqr, orgqr... is faster, but as always with performance stuff testing it is really the best way to find out.
Maybe you could write a test for this with some simple time measurements using MKL?

If it (as we I think both agree) turns out to be faster using orgqr's, then we should use that whenever possible.
However, if this complicated the code too much it might be good to wait on it for a bit.
Either way, we'll need a simple test to check the performance!
